# Generated by Django 5.2.5 on 2025-08-27 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('name_ext', models.CharField(blank=True, verbose_name='Additional context to remember them by')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('how_we_met', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_people', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone Call'), ('text', 'Text Message'), ('email', 'Email'), ('video', 'Video Call'), ('other', 'Other')])),
                ('location', models.CharField(blank=True)),
                ('notes', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='conversations', to='orbit.person')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('text', 'Text Message'), ('email', 'Email'), ('call', 'Phone Call'), ('social', 'Social Media'), ('other', 'Other')])),
                ('notes', models.TextField(blank=True)),
                ('private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contact_attempts', to=settings.AUTH_USER_MODEL)),
                ('led_to_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orbit.conversation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='orbit.person')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('partner', 'Partner'), ('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('acquaintance', 'Acquaintance'), ('other', 'Other')])),
                ('description', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person1', to='orbit.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person2', to='orbit.person')),
            ],
            options={
                'unique_together': {('person1', 'person2')},
            },
        ),
    ]
