# Generated by Django 5.2.5 on 2025-08-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0002_alter_contactattempt_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, verbose_name='City or state'),
        ),
    ]
