# Generated by Django 5.2.5 on 2025-09-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_person_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True),
        ),
    ]
