# Generated by Django 5.2.5 on 2025-09-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0004_person_address_person_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactattempt',
            name='led_to_conversation',
            field=models.BooleanField(default=False),
        ),
    ]
