# Generated by Django 5.2.5 on 2025-09-02 01:00

from django.db import migrations


def migrate_birthday_data_forward(apps, schema_editor):
    """Migrate existing birthday data to new fields"""
    Person = apps.get_model('orbit', 'Person')
    
    for person in Person.objects.all():
        if person.birthday:
            person.birthday_month = person.birthday.month
            person.birthday_day = person.birthday.day
            person.birth_year = person.birthday.year
            person.save()


def migrate_birthday_data_reverse(apps, schema_editor):
    """Reverse migration: restore birthday from component fields"""
    Person = apps.get_model('orbit', 'Person')
    from datetime import date
    
    for person in Person.objects.all():
        if person.birthday_month and person.birthday_day and person.birth_year:
            try:
                person.birthday = date(person.birth_year, person.birthday_month, person.birthday_day)
                person.save()
            except ValueError:
                # Skip invalid dates
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0006_separate_birthday_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_birthday_data_forward, migrate_birthday_data_reverse),
    ]