# Generated by Django 5.2.5 on 2025-09-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0007_migrate_birthday_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
    ]